# Documentation:
# - alacritty(5)
# - alacritty-bindings(5)
# - https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
#:schema https://github.com/distinction-dev/alacritty-schema/raw/refs/heads/main/alacritty/reference.json
#:tombi toml-version = "v1.1.0"

# navigation
[[keyboard.bindings]]
key = "Up"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Control|Shift"
action = "ScrollLineDown"

# editing
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\x17"

[[keyboard.bindings]]
key = "Delete"
mods = "Control"
chars = "\x1bd"

# external tools
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "SpawnNewInstance"

# For Claude Code
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001B[13;5u"
