#!/bin/sh

# Install all packages that are subdirs of this directory.
#
# The target directory is $HOME.
# To "restow", use `-R`.
#
# Refer to stow(1) for other command line options.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
find "$DIR" -maxdepth 1 -mindepth 1 -name ".git" -prune -o -type d -printf "%f\\n" | xargs stow --dir="$DIR" --target="$HOME" $*
