#!/usr/bin/zsh

input_file=${1-/dev/stdin}

tmp_file=$(mktemp)
trap "rm -f '$tmp_file'" 0

<$input_file tee "$tmp_file" | wc -lL | LFS=' ' read lines chars _
echo "lines: $lines, chars: $chars"

<$tmp_file \
    ~/.config/polybar/scripts/polyyad.py --nobuttons --text-info --no-buttons --close-on-unfocus \
    --height $((lines * 19 + 10)) \
    --width $((chars * 10))
