#!/usr/bin/env bash

pactl subscribe \
    | while :; do
        default_sink=$(pactl info | rg -o --pcre2 'Default Sink: (.*)' -r '$1')
        sinkicon=""
        case "$default_sink" in
            *Lenovo_ThinkPad_USB-C_Dock_Audio*|*Focusrite_Scarlett_Solo_USB_*)
                # Unicode:
                # sinkicon="🖥"
                # Font Awesome:
                sinkicon=""
                ;;
            alsa_output.usb-*)
                sinkicon=""
                ;;
            *hdmi*|*HDMI*)
                # Unicode:
                # sinkicon="🖵"
                # FontAwesome 7:
                sinkicon=""
                ;;
        esac
        sourceicon=$([[ "$(pactl get-source-mute "$(pactl get-default-source)")" = "Mute: yes" ]] && echo -n "")
        [[ -z "$sinkicon$sourceicon" ]] && echo || echo "$sourceicon $sinkicon"
        while
            # wait until something relevant changed
            read -r line && [[ ! "$line" =~ "on sink" ]] && [[ ! "$line" =~ "on source" ]] && [[ ! "$line" =~ "on server" ]]
        do :; done
    done
