#!/usr/bin/env bash

pactl subscribe \
    | while :; do
        sinkicon=$(pactl info | rg -q --pcre2 'Default Sink:.*(alsa_output\.usb-Plantronics_Plantronics_Blackwire_5220_Series)' && echo -n "")
        sourceicon=$([[ "$(pactl get-source-mute "$(pactl get-default-source)")" = "Mute: yes" ]] && echo -n "")
        [[ -z "$sinkicon$sourceicon" ]] && echo || echo "$sourceicon $sinkicon"
        while
            # wait until something relevant changed
            read -r line && [[ ! "$line" =~ "on sink" ]] && [[ ! "$line" =~ "on source" ]] && [[ ! "$line" =~ "on server" ]]
        do :; done
    done
