#!/bin/sh

# See .git/hooks/pre-push.sample for documentation.

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [[ "$local_ref" == *private* ]]; then
		# prevent pushing "private" refs
		echo >&2 "$local_ref is a private ref, not pushing"
		exit 1
	fi

	if [ "$remote_sha" = $z40 ]; then
		# New branch, examine all commits
		range="$local_sha"
	else
		# Update to existing branch, examine new commits
		range="$remote_sha..$local_sha"
	fi

	commit=`git rev-list -n 1 --grep '^!!' "$range"`
	if [ -n "$commit" ]; then
		echo >&2 "Found local-only commit in $local_ref, not pushing"
		exit 1
	fi
done

exit 0
